name: Java CI with Gradle and Docker

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle
      - name: Run Tests
        run: ./gradlew test

  build:
    needs: tests
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: "11"
          distribution: "adopt"
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: demojavaman/java-gradle-demo
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }} # add DOCKER_USERNAME and value in settings/secrets
          password: ${{ secrets.DOCKER_PASSWORD }} # add DOCKER_PASSWORD and value in settings/secrets
